


#链接battery例程所需的依赖如下

ALL_FILE += \
		   ../build/Objects/common/dji_linux_environment.o \
		   ../build/Objects/battery/get_Telemetry.o \
		   ../build/Objects/platform/linux/hal/osdkhal_linux.o \
		   ../build/Objects/platform/linux/osal/osdkosal_linux.o \
		   ../build/Objects/common/dji_linux_helpers.o \
		   ../build/Objects/osdk-core/api/src/dji_battery.o \
		   ../build/Objects/osdk-core/logger/src/dji_log.o \
		   ../build/Objects/osdk-core/api/src/dji_battery_impl.o \
		   ../build/Objects/osdk-core/api/src/dji_version.o \
		   ../build/Objects/osdk-core/utility/src/dji_setup_helpers.o \
		   ../build/Objects/osdk-core/platform/src/dji_platform.o \
		   ../build/Objects/osdk-core/api/src/dji_vehicle.o \
		   ../build/Objects/osdk-core/api/src/dji_ack.o \
		   ../build/Objects/osdk-core/api/src/dji_camera.o \
		   ../build/Objects/osdk-core/api/src/dji_gimbal.o \
		   ../build/Objects/osdk-core/api/src/dji_subscription.o \
		   ../build/Objects/osdk-core/api/src/dji_error.o \
		   ../build/Objects/osdk-core/api/src/dji_command.o \
		   ../build/Objects/osdk-core/api/src/dji_mfio.o \
		   ../build/Objects/osdk-core/api/src/dji_legacy_linker.o \
		   ../build/Objects/osdk-core/api/src/dji_mobile_device.o \
		   ../build/Objects/osdk-core/api/src/dji_payload_device.o \
		   ../build/Objects/osdk-core/advanced-sensing/api/src/dji_advanced_sensing.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/src/dji_camera_stream.o \
		   ../build/Objects/osdk-core/api/src/dji_camera_manager.o \
		   ../build/Objects/osdk-core/api/src/dji_psdk_manager.o \
		   ../build/Objects/osdk-core/advanced-sensing/api/src/dji_liveview_impl.o \
		   ../build/Objects/osdk-core/advanced-sensing/api/src/dji_liveview.o \
		   ../build/Objects/osdk-core/advanced-sensing/api/src/dji_perception_impl.o \
		   ../build/Objects/osdk-core/advanced-sensing/api/src/dji_perception.o \
		   ../build/Objects/osdk-core/api/src/dji_broadcast.o \
		   ../build/Objects/osdk-core/api/src/dji_mission_manager.o \
		   ../build/Objects/osdk-core/modules/src/firewall/osdk_firewall.o \
		   ../build/Objects/osdk-core/api/src/dji_waypoint_v2.o \
		   ../build/Objects/osdk-core/api/src/dji_hms.o \
		   ../build/Objects/osdk-core/api/src/dji_flight_controller.o \
		   ../build/Objects/osdk-core/advanced-sensing/ori-osdk-core/utility/src/dji_singleton.hpp \
		   ../build/Objects/osdk-core/api/src/dji_hardware_sync.hpp \
		   ../build/Objects/osdk-core/api/src/dji_hotpoint.hpp \
		   ../build/Objects/osdk-core/api/src/dji_waypoint.hpp \
		   ../build/Objects/osdk-core/modules/src/payload/dji_camera_module.hpp \
		   ../build/Objects/osdk-core/modules/src/payload/dji_payload_base.hpp \
		   ../build/Objects/osdk-core/modules/src/filemgr/dji_file_mgr.hpp \
		   ../build/Objects/osdk-core/modules/src/filemgr/dji_file_mgr_define.hpp \
		   ../build/Objects/osdk-core/api/src/dji_gimbal_manager.hpp \
		   ../build/Objects/osdk-core/modules/src/payload/dji_gimbal_module.hpp \
		   ../build/Objects/osdk-core/modules/src/payload/dji_payload_link.hpp \
		   ../build/Objects/osdk-core/modules/src/flight/dji_flight_assistant_module.hpp \
		   ../build/Objects/osdk-core/modules/src/flight/dji_flight_joystick_module.hpp \
		   ../build/Objects/osdk-core/modules/src/payload/dji_psdk_module.hpp \
		   ../build/Objects/osdk-core/modules/src/mop/dji_mop_client.hpp \
		   ../build/Objects/osdk-core/modules/src/mop/dji_mop_pipeline.hpp \
		   ../build/Objects/osdk-core/modules/src/mop/dji_mop_define.hpp \
		   ../build/Objects/osdk-core/modules/src/mop/dji_mop_pipeline_manager_base.hpp \
		   ../build/Objects/osdk-core/modules/src/mop/dji_mop_server.hpp \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/src/dji_camera_stream_decoder.o \
		   ../build/Objects/osdk-core/advanced-sensing/protocol/src/dji_advanced_sensing_protocol.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/src/dji_camera_stream_link.o \
		   ../build/Objects/osdk-core/modules/src/filemgr/impl/commondatarangehandler.o \
		   ../build/Objects/osdk-core/api/src/dji_hms_impl.o \
		   ../build/Objects/osdk-core/api/src/dji_hms_internal.o \
		   ../build/Objects/osdk-core/modules/src/filemgr/impl/mmap_file_buffer.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/api.o \
		   ../build/Objects/osdk-core/modules/src/filemgr/impl/dji_file_mgr_impl.o \
		   ../build/Objects/osdk-core/modules/src/filemgr/impl/downloadbufferqueue.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/buffer.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/cache.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/ccc.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/channel.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/common.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/core.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/epoll.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/list.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/md5.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/packet.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/queue.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/udt/src/window.o \
		   ../build/Objects/osdk-core/advanced-sensing/camera_stream/src/dji_camera_image_handler.o \
		   ../build/Objects/osdk-core/modules/src/flight/dji_flight_actions_module.o \
		   ../build/Objects/osdk-core/modules/src/flight/dji_flight_link.o   \
		   ../build/Objects/osdk-core/advanced-sensing/ori-osdk-core/protocol/src/dji_protocol_base.o \
		   ../build/Objects/osdk-core/advanced-sensing/ori-osdk-core/hal/src/dji_thread_manager.o \
		   ../build/Objects/osdk-core/advanced-sensing/ori-osdk-core/platform/linux/src/posix_thread_manager.o \
		   ../build/Objects/osdk-core/advanced-sensing/platform/src/linux_usb_device.o \
		   ../build/Objects/osdk-core/advanced-sensing/ori-osdk-core/hal/src/dji_hard_driver.o \
		   ../build/Objects/osdk-core/advanced-sensing/ori-osdk-core/hal/src/dji_memory.o \
		   /home/lan/comdin/Dji_SDK/mysample/build/Objects/osdk-core/api/src/dji_control.o \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libusb-1.0.a \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libavcodec.a \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libavformat.a \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libavutil.a \
		   /home/lan/comdin/Dji_SDK/lib/FFmpeg-n4.4/libswresample/libswresample.a \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libswscale.a \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libz.a \
		   ../osdk-core/linker/armv7/lib/libdji-linker.a \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libavcodec.a \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libavformat.a \
		   /usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib/libavutil.a \
		   /home/lan/comdin/Dji_SDK/lib/libusb-1.0.24/libusb/.libs/libusb-1.0.a \
		   /home/lan/comdin/Dji_SDK/lib/FFmpeg-n4.4/libswresample/libswresample.a \

#ALL_FILE += $(shell find ../ -name *.o)

#
#将ALL_FILE中所有.h .hpp的头文件换成 .o 并且删除所有main.o
ALL_FILE := $(patsubst %.h,%.o,$(ALL_FILE))
ALL_FILE := $(patsubst %.hpp,%.o,$(ALL_FILE))
ALL_FILE := $(patsubst %/main.o, %,$(ALL_FILE))


ALL_FILES = $(ALL_FILE)


#以下同根目录下的makefile的相同代码的解释



#$(info $(ALL_FILES))
CUR_INCLUDE_DIR = ${patsubst ./%, $(ROOT_DIR)/%, $(INCLUDE_DIR)}

all:
	@echo LD battery
	@$(CXX)  ../build/Objects/battery/main.o $(ALL_FILES) -pthread -g -fPIC -g -o battery

ECHO:
	@echo $(SUBDIRS)

clean:
	rm ./battery